name: CI

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest
    

  - name: Install lcov
    run: sudo apt-get install -y lcov 
  
  - name: Configurate
    run: |
      rm -rf ${{github.workspace}}/_build
      mkdir _build && cd _build
      cmake .. -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS='--coverage'
      cmake --build .

  - name: Run tests
    run: _build/my_test
      
  - name: lcov
    run: lcov -c -d _build/CMakeFiles/banking.dir/banking/ --include *.cpp --output-file ./coverage/lcov.info
  
  - name: Coveralls
    uses: coverallsapp/github-action@v2
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }} 
      path-to-lcov: ${{ github.workspace }}/coverage/lcov.info